org.gradle.jvmargs=-Xmx2G
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-25.0.1.8-hotspot

# Plugin Metadata
plugin_group=Code Creature
plugin_name=Stencil Crafting
plugin_description=Stencil Crafting system with Blueprint Book item workflows
plugin_author=CodeCreature
plugin_website=
plugin_main_entrypoint=com.CodeCreature.Plugin
server_version=2026.03.26-89796e57b
