org.gradle.jvmargs=-Xmx2G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=Camera
plugin_description=Blueprint crafting and stencil placement system
plugin_author=CodeCreature
plugin_website=
plugin_main_entrypoint=com.CodeCreature.Plugin
server_version=2026.03.26-89796e57b
